services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weatherData

  mongodb:
    image: mongo:5.0
    container_name: openGTO-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
